### ISSUE TITLE
New chapter: Building an Open Culture, One Small Project at a Time

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization-ambassadors/open-org-leaders-manual#2]
Abstract: 
Conventional organizations have a difficult time understanding how they can transform their culture using the Open values. Often, the change feels overwhelming and the advice feels too theoretical and "pie in the sky".  However, there are practical ways that leaders can use to start being more open and using the Open Org values. 

This chapter begins by asking "what is culture?" and describes how time-bound project definitions and open values can be used to transform organizational culture.

**Comment by semioticrobotic** [comment]
Thanks for the submission, @HeidiHVL!

Is it safe to say that this is specifically about the way that leaders can effect change on smaller, project-oriented teams as a way of cultivating openness from the "bottom up"? Something like a guide for leaders hoping to practice openness in a way that needn't involve overhauling the entire organization? I am just trying to specify the scope here, because I feel something like "[...] there are practical ways that leaders can use to start being more open and using the Open Org values" could work as a description of the entire _Open Organization Workbook_!

**Comment by HeidiHVL** [comment]
Thanks for the comment @semioticrobotic !

As I was formulating a response, I thought maybe it would be good to make sure I understand the difference between the leaders manual and the workbook. The manual seems to be more "things for leaders to consider" where as the workbook is more "ways to do things".

If that is the case, then the proposed chapter would be scoped as a theoretical chapter on how the elements of projects can intersect with the dynamicism of open -- as you say -- to practice openness (and evangelize openness) in a time-bound and project-bound way that doesn't involve overhauling the whole org. 

Thanks!

**Comment by semioticrobotic** [comment]
Thanks very much for this explanation, which makes perfect sense to me and certainly seems like a great chapter in the book. I've added you to the [table of contents](https://github.com/open-organization-ambassadors/open-org-leaders-manual/blob/master/second-edition/table-of-contents.md)!

**Comment by semioticrobotic** [comment]
This chapter is currently in editing and I'll have some feedback for you soon, @HeidiHVL!
