### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by stephwright** [open-organization-ambassadors/open-org-leaders-manual#24]
Hi there, Not sure if this had already been discussed and I missed it... I was wondering if there was a possibility of walking the walk and move from CC-BY-SA to at least CC-BY?  Mostly b/c the license stacking issues that come with an SA restriction can cause so many problems for folks who want to remix our materials.  CC-BY is the most restrictive license (other than CC0, which isn't really a license) recommended by the Open Access Scholarly Publishers Assn: https://oaspa.org/why-cc-by/

**Comment by semioticrobotic** [comment]
I'm happy to listen to additional perspectives here, because I'm certainly not a licensing expert. By way of providing context, however, I can at least note that the SA parameter helps us align with Opensource.com more generally. Indeed, some of the book chapters actually begin as articles on Opensource.com and are already licensed BY-SA, so we'd need to keep that parameter in place for a good chunk of the materials anyway. Other "book first" materials would then be CC BY, leading to volumes containing individual chapters with different licenses. Historically, we've used the SA parameter as a way of ensuring that all the materials "remain open," and (assuming you meant to write that CC BY was the "most permissive" in your explanation above), this has been the easiest and most painless way to do that.

But, as I said: Happy to hear from others.

**Comment by funnelfiasco** [comment]
I'm a copyleft-by-default kind of person, so I'm in favor of keeping it CC BY-SA.

**Comment by semioticrobotic** [comment]
Seeing no broader consensus on a need to change our approach to copyright, I'll close this now with the intent to reopen should our approach need adjustment in the future.
